# Generated by Django 5.0.4 on 2025-07-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
