# Generated by Django 5.0.4 on 2025-07-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
